### PR TITLE
Add new icons to Astro

### PR DESCRIPTION
**Pull request by brunobc182**
# What

This __PR__ adds new icons to Astro.

### CODE REVIEW

**Comment by AgtLucas** [comment]
> The code looks okay, but something's off with some of the card sizes 🤔
> Screen Shot 2019-08-08 at 15 28 37

@larimaza @brunobc182 That's because of the long text right below the icons.

The [IconsCollection](https://github.com/magnetis/astro/blob/master/docs/components/IconsCollection.jsx#L5) is a flex element, so we gonna need to tweak the text to either break in multiple lines when needed or truncate it.

**Comment by brunobc182** [comment]
> > The code looks okay, but something's off with some of the card sizes 🤔
> > Screen Shot 2019-08-08 at 15 28 37
> 
> @larimaza @brunobc182 That's because of the long text right below the icons.
> 
> The [IconsCollection](https://github.com/magnetis/astro/blob/master/docs/components/IconsCollection.jsx#L5) is a flex element, so we gonna need to tweak the text to either break in multiple lines when needed or truncate it.
> 
> I think we could merge this PR and fix the `IconsCollection` in another PR.

Yep i didn't notice this. I can fix it here or in another PR. What do you think? @larimaza @AgtLucas .

**Comment by AgtLucas** [comment]
> > > The code looks okay, but something's off with some of the card sizes 🤔
> > > Screen Shot 2019-08-08 at 15 28 37
> > 
> > 
> > @larimaza @brunobc182 That's because of the long text right below the icons.
> > The [IconsCollection](https://github.com/magnetis/astro/blob/master/docs/components/IconsCollection.jsx#L5) is a flex element, so we gonna need to tweak the text to either break in multiple lines when needed or truncate it.
> > I think we could merge this PR and fix the `IconsCollection` in another PR.
> 
> Yep i didn't notice this. I can fix it here or in another PR. What do you think? @larimaza @AgtLucas.

@brunobc182 Thinking about releases and changelogs, I would fix it in another PR, but it's up to you!

**Comment by larimaza** [comment]
Great catch @AgtLucas, 

> > > > The code looks okay, but something's off with some of the card sizes 🤔
> > > > Screen Shot 2019-08-08 at 15 28 37
> > > 
> > > 
> > > @larimaza @brunobc182 That's because of the long text right below the icons.
> > > The [IconsCollection](https://github.com/magnetis/astro/blob/master/docs/components/IconsCollection.jsx#L5) is a flex element, so we gonna need to tweak the text to either break in multiple lines when needed or truncate it.
> > > I think we could merge this PR and fix the `IconsCollection` in another PR.
> > 
> > 
> > Yep i didn't notice this. I can fix it here or in another PR. What do you think? @larimaza @AgtLucas.
> 
> @brunobc182 Thinking about releases and changelogs, I would fix it in another PR, but it's up to you!

Great catch @AgtLucas, I looked quickly through the code and didn't detect the cause.
I don't think it would hurt to fix it in this same PR :D As it's adjusting the doc only, and not the Astro deliverable, it doesn't really affect releases :)

**Pull request merged**
